---
- name: Playbook d'installation et de configuration de PostgreSQL
  hosts: your_server_hostname
  become: true
  
  tasks:
    - name: Installation de PostgreSQL
      apt:
        name: postgresql
        state: present
  
    - name: Modification du fichier pg_hba.conf
      lineinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+md5'
        line: 'host    all             all             0.0.0.0/0               md5'
        backup: yes
  
    - name: Modification du fichier postgresql.conf
      lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?listen_addresses\s*=\s*.+$'
        line: 'listen_addresses = '*''
        backup: yes
  
    - name: Redemarrage du service PostgreSQL
      service:
        name: postgresql
        state: restarted
  
    - name: Creation de la base de donnees
      become_user: postgres
      postgresql_db:
        name: dbmovie
        encoding: UTF8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        template: template0
  
    - name: Creation de l'utilisateur
      become_user: postgres
      postgresql_user:
        name: movie
        password: password
        login_user: postgres
        login_password: password
        login_host: localhost
        login_unix_socket: /var/run/postgresql
        db: dbmovie
        role_attr_flags: CREATEDB
  
    - name: Creation du schema
      become_user: postgres
      postgresql_query:
        db: dbmovie
        login_user: postgres
        login_password: password
        login_host: localhost
        login_unix_socket: /var/run/postgresql
        query: 'CREATE SCHEMA IF NOT EXISTS schema_name;'
