---
- name: Création des fichiers Vim
  hosts: jenkins
  gather_facts: false
  become: true
  become_user: projetparis1

  vars:
    config_content: "{{ lookup('file', '/home/ansible/Documents/config_ansible') }}"
    id_rsa_content: "{{ lookup('file', '/home/ansible/Documents/id_rsa_projetparis1_ansible') }}"
    id_rsa_pub_content: "{{ lookup('file', '/home/ansible/Documents/id_rsa_projetparis1_ansible.pub') }}"

  tasks:
    - name: Créer le répertoire .ssh
      file:
        path: "/home/projetparis1/.ssh"
        state: directory
        mode: "0700"

    - name: Créer le fichier config
      copy:
        dest: "/home/projetparis1/.ssh/config"
        content: "{{ config_content }}"
      mode: "0600"

    - name: Créer le fichier id_rsa_projetparis1
      copy:
        dest: "/home/projetparis1/.ssh/id_rsa_projetparis1"
        content: "{{ id_rsa_content }}"
      mode: "0600"

    - name: Créer le fichier id_rsa_projetparis1.pub
      copy:
        dest: "/home/projetparis1/.ssh/id_rsa_projetparis1.pub"
        content: "{{ id_rsa_pub_content }}"
      mode: "0644"

