---
- name: Récupérer et envoyer un fichier
  hosts: springboot
  gather_facts: false

  tasks:
    - name: Récupérer le fichier depuis la machine source
      delegate_to: 192.168.121.148
      fetch:
        src: /home/ansible/PROJET-POEI/ANSIBLE/Configuration/stockage/movieapi.jar  # Chemin du fichier sur la machine source
        dest: ./stockage  # Chemin de destination sur la machine locale

    - name: Envoyer le fichier vers la machine de destination
      copy:
        src: /home/ansible/PROJET-POEI/ANSIBLE/Configuration/stockage/movieapi.jar  # Chemin du fichier récupéré
        dest: /home/springboot/stockage  # Chemin de destination sur la machine de destination

