name: installer nagios 
  hosts: nagios
  become: true

  tasks:
    - name: Installer les dépendances
      apt:
        name:
          - build-essential
          - apache2
          - php
          - libgd-dev
          - libapache2-mod-php
          - libperl-dev
          - libssl-dev
          - daemontools
        state: present

    - name: Télécharger Nagios
      get_url:
        url: "https://www.nagios.org/downloads/nagios-core/latest/nagios-nagios-4.4.6.tar.gz"
        dest: /tmp/nagios.tar.gz

    - name: Extraire les fichiers de Nagios
      unarchive:
        src: /tmp/nagios.tar.gz
        dest: /tmp/nagios

    - name: Compiler et installer Nagios
      command: |
        cd /tmp/nagios
        ./configure --with-command-group=nagcmd
        make all
        make install
        make install-commandmode
        make install-init
        make install-config
        make install-webconf
      args:
        chdir: /tmp/nagios
      register: nagios_install

    - name: Vérifier l'installation de Nagios
      assert:
        that:
          - nagios_install.rc == 0
        msg: "L'installation de Nagios a échoué."

    - name: Ajouter un utilisateur Nagios
      user:
        name: nagios
        comment: "nagios"
        shell: /sbin/nologin
        createhome: no

    - name: nagios
      group:
        name: nagcmd
        state: present

    - name: Ajouter l'utilisateur Nagios au groupe nagcmd
      user:
        name: nagios
        groups: nagcmd
        append: yes

    - name: Définir un mot de passe pour l'utilisateur Nagios
      shell: echo "nagios:<password>" | chpasswd
      args:
        executable: /bin/bash
      vars_prompt:
        - name: password
          prompt: "password :  "
          private: yes

    - name: Démarrer les services Nagios et Apache
      service:
        name: "{{ début }}"
        state: started
        enabled: yes
      loop:
        - nagios
        - apache2
