---
- name: Installer Nagios
  hosts: nagios
  become: true

  tasks:
    - name: Mise a jour des paquets
      apt:
        update_cache: yes
        upgrade: safe

    - name: Installation des paquets requis
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - php
          - wget
          - unzip
          - zip
          - autoconf
          - gcc
          - libc6
          - make
          - apache2-utils
          - libgd-dev
        state: present

    - name: Demarrage du service Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Telechargement de Nagios
      get_url:
        url: "https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz"
        dest: /tmp/nagios.tar.gz

    - name: Creer le repertoire de destination
      file:
        path: /tmp/nagios
        state: directory      
    
    - name: Copy Nagios to user's home directory
      copy:
        src: "tmp/nagios.tar.gz"
        dest: "/home/nagios/nagios.tar.gz"
        remote_src: yes
        owner: nagios
        group: nagios
        mode: "0644"

    - name: Extraction des fichiers de Nagios
      unarchive:
        src: /home/nagios/nagios.tar.gz
        dest: /home/nagios
        remote_src: yes

    - name: Modification du groupe de l'utilisateur www-data
      command: usermod -a -G nagios www-data
    
    - name: Configuration de Nagios
      command: >
        ./configure --with-httpd-conf=/etc/apache2/sites-enabled
        chdir: /home/nagios/nagios-4.4.6

    - name: Compilation et installation de Nagios
      command: make all && make install && make install-init && make install-commandmode && make install-config && make install-webconf
      args:
        chdir: /home/nagios/nagios-4.4.6

    - name: Activation du module CGI pour Apache
      command: a2enmod cgi

    - name: Redemarrage du service Apache
      service:
        name: apache2
        state: restarted

    - name: Demarrage du service Nagios
      service:
        name: nagios
        state: started

    - name: Configuration du fichier de mots de passe
      command: htpasswd -c /usr/local/nagios/etc/htpasswd.users Alviss
      args:
        creates: /usr/local/nagios/etc/htpasswd.users
