---
- name: install postgres
  hosts: postgresql
  tasks:
    - name: install ACL
      ansible.builtin.apt:
        name: acl
        state: present


- name: install postgresql and start service
  hosts: postgresql 
  tasks:
    - name: install postgresql db
      ansible.builtin.apt:
        name: postgresql-{{ pg_version }}
        state: present 
    - name: Start service postgres
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

- name: Create a new database with name "{{ dbname }}"
  hosts: postgresql
  become_user: postgres
  tasks:
    - name: create database
      community.postgresql.postgresql_db:
        state: present
        name: "{{ dbname }}"

    - name: create database user
      become_user: postgres
      community.postgresql.postgresql_user:
        state: present
        name: "{{ dbuser }}"
        password: "{{ dbpassword }}"

    - name: Create a new schema with name movie in test database
      become_user: postgres
      community.postgresql.postgresql_schema:
        name: "{{ dbschema }}"
        state: present

    - name: stop service postgres for change configue
      ansible.builtin.service:
        name: postgresql
        state: stopped

    - name: modify postgresql.conf - listen_adresses localhost to --> *
      ansible.builtin.lineinfile:
        path: /etc/postgresql/{{ pg_version }}/main/postgresql.conf
        regexp: "^#?listen_addresses = '.*'*$"
        line: "listen_addresses = '*'"
        state: present

    - name: "allow md5 connection for the db user"
      ansible.builtin.lineinfile:
        path: /etc/postgresql/{{ pg_version }}/main/pg_hba.conf
        regexp: "^host\\s+all\\s+all\\s+127.0.0.1/32\\s+md5"
        line: "host {{dbname}} {{dbuser}}  0.0.0.0/0   md5"
        backup: yes

    - name: Start service postgres
      ansible.builtin.service:
        name: postgresql
        state: started

