---
- name: create user jaroperator and install java 17
  hosts: springboot
  tasks:
    - name: create user jaroperator
      ansible.builtin.user:
        name: jaroperator
        createhome: yes
        shell: /bin/bash

- name: Install OpenJDK 17
  hosts: springboot
  become: yes
  tasks:
    - name: Install OpenJDK 17 package
      package:
        name: openjdk-17-jdk
        state: present
